/**
 * Seed the pledge-class and brother roster from prisma/seed-data/roster.json
 * (generated by scripts/build-roster-json.py from the historical spreadsheet).
 *
 * Idempotent: classes and brothers are matched by their natural keys (class
 * name; crossing number, or name+class for the numberless transfer) and
 * upserted, so re-running reconciles rather than duplicates. Uploaded photos
 * (BrotherPhoto rows) are never touched here.
 *
 * Run with:  npm run db:seed
 */
import "dotenv/config";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { prisma } from "../lib/prisma.ts";

type SeedClass = { name: string; term: string | null; sortOrder: number };
type SeedBrother = {
  key: string;
  crossingNumber: number | null;
  firstName: string | null;
  lastName: string | null;
  pledgeName: string;
  className: string;
  status: "ACTIVE" | "ALUMNI";
  major: string | null;
  gradYear: number | null;
  instagram: string | null;
  photoUrl: string | null;
  bigKey: string | null;
  bigNameFallback: string | null;
};

const here = dirname(fileURLToPath(import.meta.url));
const data = JSON.parse(
  readFileSync(join(here, "seed-data", "roster.json"), "utf8")
) as { classes: SeedClass[]; brothers: SeedBrother[] };

async function main() {
  // 1. Classes -------------------------------------------------------------
  const classIdByName = new Map<string, string>();
  for (const c of data.classes) {
    const row = await prisma.pledgeClass.upsert({
      where: { name: c.name },
      create: { name: c.name, term: c.term, sortOrder: c.sortOrder },
      update: { term: c.term, sortOrder: c.sortOrder },
    });
    classIdByName.set(c.name, row.id);
  }

  // 2. Brothers (without big links yet) ------------------------------------
  const idByKey = new Map<string, string>();
  for (const b of data.brothers) {
    const classId = classIdByName.get(b.className);
    if (!classId) throw new Error(`Unknown class '${b.className}' for ${b.key}`);

    const fields = {
      firstName: b.firstName ?? "",
      lastName: b.lastName,
      pledgeName: b.pledgeName,
      status: b.status,
      major: b.major,
      gradYear: b.gradYear,
      instagram: b.instagram,
      photoUrl: b.photoUrl,
      classId,
    };

    let id: string;
    if (b.crossingNumber !== null) {
      const row = await prisma.brother.upsert({
        where: { crossingNumber: b.crossingNumber },
        create: { crossingNumber: b.crossingNumber, ...fields },
        update: fields,
      });
      id = row.id;
    } else {
      // Numberless brother (transfer): match on name within the class.
      const existing = await prisma.brother.findFirst({
        where: { pledgeName: b.pledgeName, lastName: b.lastName, classId },
      });
      const row = existing
        ? await prisma.brother.update({ where: { id: existing.id }, data: fields })
        : await prisma.brother.create({ data: fields });
      id = row.id;
    }
    idByKey.set(b.key, id);
  }

  // 3. Big / little links --------------------------------------------------
  let linked = 0;
  let fallbacks = 0;
  for (const b of data.brothers) {
    const id = idByKey.get(b.key)!;
    const bigId = b.bigKey ? idByKey.get(b.bigKey) ?? null : null;
    if (b.bigKey && !bigId) {
      throw new Error(`${b.key}: big '${b.bigKey}' not found among seeded brothers`);
    }
    await prisma.brother.update({
      where: { id },
      data: { bigId, bigNameFallback: bigId ? null : b.bigNameFallback },
    });
    if (bigId) linked++;
    else if (b.bigNameFallback) fallbacks++;
  }

  const active = await prisma.brother.count({ where: { status: "ACTIVE" } });
  const total = await prisma.brother.count();
  console.log(
    `Seeded ${data.classes.length} classes, ${total} brothers ` +
      `(${active} active), ${linked} big links, ${fallbacks} fallback bigs.`
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
